### ISSUE TITLE
Questions about CPU cores and constants

### ISSUE THREAD

**Issue by x66ccff** [samholt/DeepGenerativeSymbolicRegression#1]
Hello Samuel,

I wanted to start by saying thank you for developing the DGSR model.
I've been trying to use the DGSR model following the instructions provided in the README. However, I have come across two issues that I hope you can help me with:

1. **CPU Core Usage**: Despite setting `conf.exp.seed_runs` and `conf.exp.n_cores_task` to 1, as mentioned in the README, the program still utilizes all available CPU cores. I'm curious to know why the program isn't adhering to the specified settings and if there's a way to ensure it uses only a single CPU core.

2. **Expression Search with Constants**: I attempted to enable the model to search for expressions containing constants by setting `"function_set": ["add", "sub", "mul", "div", "sin", "cos", "exp", "log", "const"]`  Unfortunately, this led to an error: `ValueError: Incorrect function set with pre-trained model ... aborting`. Could you please guide me on how to enable the model to search for expressions with constants successfully?

Thanks a lot!

**Comment by samholt** [comment]
Hi [x66ccff](https://github.com/x66ccff),

Great to hear from you! Thank you for your interest in DGSR.

Regarding:
1. That most likely is a bug that could arise from multiple libraries using multi-processing cores. I'll look into this; thank you for bringing it to my attention.
2. Great question. You need to create a new pre-trained model, trained with constants in the pre-training dataset. You should be able to find instructions on how to do this in the readme, where you will have to define a new dataset type with the constant parameter and then use this pre-trained model at inference time. Alternatively, you could forgo pre-training a new model with constants and use a new un-trained model at inference time by editing the code to set `pre_trained_model=""`. This should produce an okay result. However, the accuracy and efficiency performance can be increased by pre-training a model instead.

I hope this helps. Please don't hesitate to reach out if you have any other questions or further issues.

All the best,
Sam
