### ISSUE TITLE
Fitting Custom Data to DGSR Model

### ISSUE THREAD

**Issue by WandererXX** [samholt/DeepGenerativeSymbolicRegression#2]
Hi Samuel,

I'm curious about how to fit my custom data, like a `data.csv` file, to the DGSR model. Could you tell me how to make it work with my datasets?

Thanks!

**Comment by samholt** [comment]
Hi [WandererXX](https://github.com/WandererXX),

Great to hear from you! This code uses the same data-loading library as [https://github.com/dso-org/deep-symbolic-optimization](https://github.com/dso-org/deep-symbolic-optimization). Therefore, I would follow their instructions on how to load a custom dataset, and edit the config within this code.

I hope this helps; if you have any further questions, please do let me know,

All the best,
Sam
